variable "ec2_instance_config" {
  description = <<DESC
EC2 instance configuration object.

instance_count: Number of EC2 instances to create.
ami: AMI ID to use for the instance(s).
instance_type: EC2 instance type (e.g., 't3.medium').
key_name: Name of the EC2 Key Pair for SSH access.
subnet_id: Subnet ID for the instance(s). Should be a private subnet. Can be auto-populated from remote state or set manually.
vpc_security_group_ids: List of security group IDs to associate with the instance(s). Can be auto-populated from SG modules or remote state.
iam_instance_profile: Name of the IAM instance profile to attach to the instance(s). Can be generated by the IAM module.
root_block_device: Object describing the root block device (volume_size in GB, volume_type e.g., 'gp3').
user_data: User data script to run on instance launch (can be templated or file reference).
tags: Map of tags to apply to the instance(s) (e.g., project, environment).
DESC
  type = object({
    instance_count         = number
    ami                    = string
    instance_type          = string
    key_name               = string
    subnet_id              = string
    vpc_security_group_ids = list(string)
    iam_instance_profile   = string
    root_block_device = object({
      volume_size = number
      volume_type = string
    })
    user_data = string
    tags      = map(string)
  })
}
