variable "ec2_cluster_config" {
  description = <<DESC
EC2 cluster configuration object.

enabled: Set to true to enable creation of the EC2 cluster. If false, no EC2 cluster resources will be created.
master_count: Number of master nodes to create.
worker_count: Number of worker nodes to create.
ami: AMI ID to use for all EC2 instances in the cluster.
master_instance_type: EC2 instance type for master nodes (e.g., 't3.medium').
worker_instance_type: EC2 instance type for worker nodes.
key_name: Name of the EC2 Key Pair for SSH access.
subnet_id: Subnet ID for all cluster instances. Should be a private subnet. Can be auto-populated from remote state or set manually.
vpc_security_group_ids: List of security group IDs to associate with all cluster instances. Can be auto-populated from SG modules or remote state.
iam_instance_profile: Name of the IAM instance profile to attach to instances. Can be generated by the IAM module.
master_user_data: User data script for master nodes (can be templated or file reference).
worker_user_data: User data script for worker nodes (can be templated or file reference).
tags: Map of tags to apply to all cluster instances (e.g., project, environment).
DESC
  type = object({
    enabled         = bool
    master_count    = number
    worker_count    = number
    ami             = string
    master_instance_type = string
    worker_instance_type = string
    key_name        = string
    subnet_id       = string
    vpc_security_group_ids = list(string)
    iam_instance_profile   = string
    master_user_data = string
    worker_user_data = string
    tags            = map(string)
  })
}
